---
title: "INFO 534 Homework 1"
author: "Rachel Sagers"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Q1(a)**

The dimension of the resulting matrix C from multiplying A times B will be 4 by 4. Matrix A is *mxn* (4,3), and matrix B is *nxo* (3,4), so the resulting matrix C will be *mxo* (4,4). 

**Q1(b)**

The value of C~2,2~ can be computed by multiplying the vector of row 2 of matrix A, by the vector of column 2 of matrix B and summing the products. The value of C~2,2~ will thus be *5(3) + 1(1) + 2(1) = 18.*

**Q1(c)**

```{r matrices}
# produce matrix A
matrixA <- matrix(c(4,5,-1,2,2,1,5,-3,2,2,1,3), nrow=4, ncol=3)

# produce matrix B
matrixB <- matrix(c(2,4,1,3,1,1,1,-3,-1,3,1,1), nrow=3, ncol=4)

# matrix multiplication
matrixC <- matrixA %*% matrixB

print(matrixC)

```

**Q2**

```{r while}
v <- 10
while(15 - v > 0.1)
{
  v <- v + runif(n=1, min=0, max=1)
  print(v)
}
```

**Q3(a)**

```{r histogram}

# 5000 random values of x and histogram
x <- runif(n=5000, min=0, max=100)
hist(x)
```

**Q3(b)**

``` {r linear model}
# put x values into linear model
a <- 0.2

output = function(a,x){
y = -1 + a*x
return(y)
}

y <- output(x=x, a=0.2)

plot(x,y)
```

**Q4**

```{r log likelihood}
# the range of the model parameter value to be considered
a.values = seq(-2,2,0.1)

# log likelihood function
logL = function(a, x, y){
  sigma = 1
  500*log(1/(sqrt(2*pi)*sigma)) - 1/((sigma^2)*(1/2)*sum((a*x - y)^2))
}
```